apiVersion: hypershift.openshift.io/v1alpha1
kind: NodePool
metadata:
  name: {{ .Release.Name }}-worker
spec:
  clusterName: {{ .Values.clusterName }}
  nodeCount: 0
  management:
    upgradeType: InPlace
    replace:
      strategy: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  platform:
    type: None
  release:
    image: {{ .Values.releaseImage }}
